import fs from 'node:fs/promises';
import path from 'node:path';
import { config } from '../config/env';
import { logger } from './logger';
import { randomToken } from './hash';

/** Creates the on-disk scratch directories the API relies on. */
export async function ensureRuntimeDirectories(): Promise<void> {
  await fs.mkdir(config.tempDir, { recursive: true });
  await fs.mkdir(config.uploadsDir, { recursive: true });
}

export async function writeTempFile(buffer: Buffer, extension: string): Promise<string> {
  await ensureRuntimeDirectories();
  const safeExtension = extension.startsWith('.') ? extension : `.${extension}`;
  const filePath = path.join(config.tempDir, `${randomToken(12)}${safeExtension}`);
  await fs.writeFile(filePath, buffer, { mode: 0o600 });
  return filePath;
}

export async function writeUpload(
  verificationId: string,
  buffer: Buffer,
  extension: string,
): Promise<string> {
  await ensureRuntimeDirectories();
  const safeExtension = extension.startsWith('.') ? extension : `.${extension}`;
  // The id is generated by the database (cuid), never by the client, so it can
  // never traverse out of the uploads directory - assert it anyway.
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(verificationId)) {
    throw new Error('Refusing to write an upload under a suspicious identifier.');
  }
  const filePath = path.join(config.uploadsDir, `${verificationId}${safeExtension}`);
  await fs.writeFile(filePath, buffer, { mode: 0o600 });
  return filePath;
}

export async function removeQuietly(filePath: string | undefined | null): Promise<void> {
  if (!filePath) return;
  try {
    await fs.unlink(filePath);
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code !== 'ENOENT') logger.warn({ filePath, err: error }, 'Failed to remove temporary file');
  }
}

/**
 * Deletes stray temp files older than `maxAgeMs`. Uploads are retained because
 * the results page displays the original image; temp scratch files are not.
 */
export async function sweepTempFiles(maxAgeMs = 60 * 60 * 1000): Promise<number> {
  let removed = 0;
  try {
    const entries = await fs.readdir(config.tempDir, { withFileTypes: true });
    const cutoff = Date.now() - maxAgeMs;
    for (const entry of entries) {
      if (!entry.isFile()) continue;
      const filePath = path.join(config.tempDir, entry.name);
      const stats = await fs.stat(filePath).catch(() => null);
      if (stats && stats.mtimeMs < cutoff) {
        await removeQuietly(filePath);
        removed += 1;
      }
    }
  } catch (error) {
    logger.warn({ err: error }, 'Temp sweep failed');
  }
  return removed;
}
